### ISSUE TITLE
Add options for color, opacity, and size

### ISSUE THREAD

**Issue by dsandstrom** [dsandstrom/atom-gutter-shadow#5]

**Comment by dsandstrom** [comment]
Allow these to be set in the UI theme.

**Comment by kankaristo** [comment]
This looks quite nice on a dark theme. :)

```
@gutter-shadow-color: rgba(255, 255, 255, .10);
```

**Comment by dsandstrom** [comment]
Thanks for the feedback.  Unfortunately, I couldn't figure out a clean way to add configs for these settings, yet.  However, I added instructions on how to change the shadow from your personal stylesheet.

In addition, I tried to allow the shadow variables to be set from within a UI theme.  But, this is not tested, so I don't know if it works.

**Comment by kankaristo** [comment]
I actually prefer customizing it through Less, because you can modify a lot more then just the color.

I added a short (0.5 second) transition, which would be very hard to define in settings.

**Edit**
And the instructions in README.md are definitely a good thing, so you don't have to go digging through the code to find what to modify. :+1:
